import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const currencies = [
  { iso4217: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { iso4217: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
  { iso4217: 'ALL', symbol: 'L', name: 'Albanian Lek' },
  { iso4217: 'AMD', symbol: '֏', name: 'Armenian Dram' },
  { iso4217: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder' },
  { iso4217: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza' },
  { iso4217: 'ARS', symbol: '$', name: 'Argentine Peso' },
  { iso4217: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { iso4217: 'AWG', symbol: 'ƒ', name: 'Aruban Florin' },
  { iso4217: 'AZN', symbol: '₼', name: 'Azerbaijani Manat' },
  { iso4217: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark' },
  { iso4217: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar' },
  { iso4217: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { iso4217: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  { iso4217: 'BHD', symbol: 'BD', name: 'Bahraini Dinar' },
  { iso4217: 'BIF', symbol: 'Fr', name: 'Burundian Franc' },
  { iso4217: 'BMD', symbol: '$', name: 'Bermudian Dollar' },
  { iso4217: 'BND', symbol: 'B$', name: 'Brunei Dollar' },
  { iso4217: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano' },
  { iso4217: 'BOV', symbol: 'BOV', name: 'Bolivian Mvdol' },
  { iso4217: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { iso4217: 'BSD', symbol: 'B$', name: 'Bahamian Dollar' },
  { iso4217: 'BTN', symbol: 'Nu', name: 'Bhutanese Ngultrum' },
  { iso4217: 'BWP', symbol: 'P', name: 'Botswana Pula' },
  { iso4217: 'BYN', symbol: 'Br', name: 'Belarusian Ruble' },
  { iso4217: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },
  { iso4217: 'CAD', symbol: 'CA$', name: 'Canadian Dollar' },
  { iso4217: 'CDF', symbol: 'Fr', name: 'Congolese Franc' },
  { iso4217: 'CHE', symbol: 'CHE', name: 'WIR Euro' },
  { iso4217: 'CHF', symbol: 'Fr', name: 'Swiss Franc' },
  { iso4217: 'CHW', symbol: 'CHW', name: 'WIR Franc' },
  { iso4217: 'CLF', symbol: 'CLF', name: 'Chilean Unit of Account (UF)' },
  { iso4217: 'CLP', symbol: '$', name: 'Chilean Peso' },
  { iso4217: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { iso4217: 'COP', symbol: '$', name: 'Colombian Peso' },
  { iso4217: 'COU', symbol: 'COU', name: 'Colombian Real Value Unit' },
  { iso4217: 'CRC', symbol: '₡', name: 'Costa Rican Colón' },
  { iso4217: 'CUP', symbol: '$', name: 'Cuban Peso' },
  { iso4217: 'CVE', symbol: '$', name: 'Cape Verdean Escudo' },
  { iso4217: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  { iso4217: 'DJF', symbol: 'Fr', name: 'Djiboutian Franc' },
  { iso4217: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  { iso4217: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
  { iso4217: 'DZD', symbol: 'دج', name: 'Algerian Dinar' },
  { iso4217: 'EGP', symbol: '£', name: 'Egyptian Pound' },
  { iso4217: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa' },
  { iso4217: 'ETB', symbol: 'Br', name: 'Ethiopian Birr' },
  { iso4217: 'EUR', symbol: '€', name: 'Euro' },
  { iso4217: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar' },
  { iso4217: 'FKP', symbol: '£', name: 'Falkland Islands Pound' },
  { iso4217: 'GBP', symbol: '£', name: 'British Pound Sterling' },
  { iso4217: 'GEL', symbol: '₾', name: 'Georgian Lari' },
  { iso4217: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
  { iso4217: 'GIP', symbol: '£', name: 'Gibraltar Pound' },
  { iso4217: 'GMD', symbol: 'D', name: 'Gambian Dalasi' },
  { iso4217: 'GNF', symbol: 'Fr', name: 'Guinean Franc' },
  { iso4217: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal' },
  { iso4217: 'GYD', symbol: '$', name: 'Guyanese Dollar' },
  { iso4217: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { iso4217: 'HNL', symbol: 'L', name: 'Honduran Lempira' },
  { iso4217: 'HTG', symbol: 'G', name: 'Haitian Gourde' },
  { iso4217: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  { iso4217: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { iso4217: 'ILS', symbol: '₪', name: 'Israeli New Shekel' },
  { iso4217: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { iso4217: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
  { iso4217: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
  { iso4217: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
  { iso4217: 'JMD', symbol: 'J$', name: 'Jamaican Dollar' },
  { iso4217: 'JOD', symbol: 'JD', name: 'Jordanian Dinar' },
  { iso4217: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { iso4217: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  { iso4217: 'KGS', symbol: 'с', name: 'Kyrgyzstani Som' },
  { iso4217: 'KHR', symbol: '៛', name: 'Cambodian Riel' },
  { iso4217: 'KMF', symbol: 'Fr', name: 'Comorian Franc' },
  { iso4217: 'KPW', symbol: '₩', name: 'North Korean Won' },
  { iso4217: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { iso4217: 'KWD', symbol: 'KD', name: 'Kuwaiti Dinar' },
  { iso4217: 'KYD', symbol: '$', name: 'Cayman Islands Dollar' },
  { iso4217: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  { iso4217: 'LAK', symbol: '₭', name: 'Lao Kip' },
  { iso4217: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound' },
  { iso4217: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee' },
  { iso4217: 'LRD', symbol: '$', name: 'Liberian Dollar' },
  { iso4217: 'LSL', symbol: 'L', name: 'Lesotho Loti' },
  { iso4217: 'LYD', symbol: 'LD', name: 'Libyan Dinar' },
  { iso4217: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham' },
  { iso4217: 'MDL', symbol: 'L', name: 'Moldovan Leu' },
  { iso4217: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary' },
  { iso4217: 'MKD', symbol: 'ден', name: 'Macedonian Denar' },
  { iso4217: 'MMK', symbol: 'K', name: 'Myanmar Kyat' },
  { iso4217: 'MNT', symbol: '₮', name: 'Mongolian Tögrög' },
  { iso4217: 'MOP', symbol: 'P', name: 'Macanese Pataca' },
  { iso4217: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya' },
  { iso4217: 'MUR', symbol: 'Rs', name: 'Mauritian Rupee' },
  { iso4217: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  { iso4217: 'MWK', symbol: 'MK', name: 'Malawian Kwacha' },
  { iso4217: 'MXN', symbol: '$', name: 'Mexican Peso' },
  { iso4217: 'MXV', symbol: 'MXV', name: 'Mexican Investment Unit' },
  { iso4217: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { iso4217: 'MZN', symbol: 'MT', name: 'Mozambican Metical' },
  { iso4217: 'NAD', symbol: '$', name: 'Namibian Dollar' },
  { iso4217: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { iso4217: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba' },
  { iso4217: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  { iso4217: 'NPR', symbol: 'Rs', name: 'Nepalese Rupee' },
  { iso4217: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  { iso4217: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial' },
  { iso4217: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa' },
  { iso4217: 'PEN', symbol: 'S/.', name: 'Peruvian Sol' },
  { iso4217: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina' },
  { iso4217: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  { iso4217: 'PKR', symbol: 'Rs', name: 'Pakistani Rupee' },
  { iso4217: 'PLN', symbol: 'zł', name: 'Polish Złoty' },
  { iso4217: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní' },
  { iso4217: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal' },
  { iso4217: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  { iso4217: 'RSD', symbol: 'din', name: 'Serbian Dinar' },
  { iso4217: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  { iso4217: 'RWF', symbol: 'Fr', name: 'Rwandan Franc' },
  { iso4217: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal' },
  { iso4217: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar' },
  { iso4217: 'SCR', symbol: 'Rs', name: 'Seychellois Rupee' },
  { iso4217: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound' },
  { iso4217: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  { iso4217: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { iso4217: 'SHP', symbol: '£', name: 'Saint Helena Pound' },
  { iso4217: 'SLE', symbol: 'Le', name: 'Sierra Leonean Leone' },
  { iso4217: 'SOS', symbol: 'Sh', name: 'Somali Shilling' },
  { iso4217: 'SRD', symbol: '$', name: 'Surinamese Dollar' },
  { iso4217: 'SSP', symbol: '£', name: 'South Sudanese Pound' },
  { iso4217: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  { iso4217: 'SVC', symbol: '₡', name: 'Salvadoran Colón' },
  { iso4217: 'SYP', symbol: '£', name: 'Syrian Pound' },
  { iso4217: 'SZL', symbol: 'L', name: 'Swazi Lilangeni' },
  { iso4217: 'THB', symbol: '฿', name: 'Thai Baht' },
  { iso4217: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni' },
  { iso4217: 'TMT', symbol: 'T', name: 'Turkmenistani Manat' },
  { iso4217: 'TND', symbol: 'DT', name: 'Tunisian Dinar' },
  { iso4217: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga' },
  { iso4217: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  { iso4217: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
  { iso4217: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar' },
  { iso4217: 'TZS', symbol: 'Sh', name: 'Tanzanian Shilling' },
  { iso4217: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  { iso4217: 'UGX', symbol: 'Sh', name: 'Ugandan Shilling' },
  { iso4217: 'USD', symbol: '$', name: 'United States Dollar' },
  { iso4217: 'USN', symbol: 'USN', name: 'US Dollar (Next day)' },
  { iso4217: 'UYI', symbol: 'UYI', name: 'Uruguayan Peso en Unidades Indexadas' },
  { iso4217: 'UYU', symbol: '$U', name: 'Uruguayan Peso' },
  { iso4217: 'UYW', symbol: 'UYW', name: 'Unidad Previsional' },
  { iso4217: 'UZS', symbol: 'лв', name: 'Uzbekistani Som' },
  { iso4217: 'VED', symbol: 'Bs.D', name: 'Venezuelan Digital Bolívar' },
  { iso4217: 'VES', symbol: 'Bs.S', name: 'Venezuelan Sovereign Bolívar' },
  { iso4217: 'VND', symbol: '₫', name: 'Vietnamese Đồng' },
  { iso4217: 'VUV', symbol: 'Vt', name: 'Vanuatu Vatu' },
  { iso4217: 'WST', symbol: 'T', name: 'Samoan Tālā' },
  { iso4217: 'XAF', symbol: 'Fr', name: 'Central African CFA Franc' },
  { iso4217: 'XAG', symbol: 'XAG', name: 'Silver (troy ounce)' },
  { iso4217: 'XAU', symbol: 'XAU', name: 'Gold (troy ounce)' },
  { iso4217: 'XBA', symbol: 'XBA', name: 'European Composite Unit' },
  { iso4217: 'XBB', symbol: 'XBB', name: 'European Monetary Unit' },
  { iso4217: 'XBC', symbol: 'XBC', name: 'European Unit of Account 9' },
  { iso4217: 'XBD', symbol: 'XBD', name: 'European Unit of Account 17' },
  { iso4217: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  { iso4217: 'XDR', symbol: 'SDR', name: 'IMF Special Drawing Rights' },
  { iso4217: 'XOF', symbol: 'Fr', name: 'West African CFA Franc' },
  { iso4217: 'XPD', symbol: 'XPD', name: 'Palladium (troy ounce)' },
  { iso4217: 'XPF', symbol: 'Fr', name: 'CFP Franc' },
  { iso4217: 'XPT', symbol: 'XPT', name: 'Platinum (troy ounce)' },
  { iso4217: 'XSU', symbol: 'XSU', name: 'SUCRE' },
  { iso4217: 'XTS', symbol: 'XTS', name: 'Reserved for testing' },
  { iso4217: 'XUA', symbol: 'XUA', name: 'ADB Unit of Account' },
  { iso4217: 'XXX', symbol: '¤', name: 'No currency' },
  { iso4217: 'YER', symbol: '﷼', name: 'Yemeni Rial' },
  { iso4217: 'ZAR', symbol: 'R', name: 'South African Rand' },
  { iso4217: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha' },
  { iso4217: 'ZWG', symbol: 'ZiG', name: 'Zimbabwe Gold' },
];

async function main() {
  console.log(`Seeding ${currencies.length} currencies...`);

  await prisma.currency.createMany({
    data: currencies,
    skipDuplicates: true,
  });

  console.log('Done.');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
